# Generated by Django 3.0.2 on 2020-01-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Abstract title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Abstract text')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_list', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Abstract',
                'verbose_name_plural': 'Abstracts',
                'ordering': ['-publish'],
            },
        ),
    ]
